/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SdButton {
        /**
          * The button size. Possible values are: `"small"`, `"default"`, `"large"`.
         */
        "size"?: 'small' | 'default' | 'large';
        /**
          * The button type. Possible values are: `"primary"`, `"secondary"`, `"disabled"`.
         */
        "type"?: 'primary' | 'secondary' | 'disabled';
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSdButtonElement extends Components.SdButton, HTMLStencilElement {
    }
    var HTMLSdButtonElement: {
        prototype: HTMLSdButtonElement;
        new (): HTMLSdButtonElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "sd-button": HTMLSdButtonElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SdButton {
        /**
          * The button size. Possible values are: `"small"`, `"default"`, `"large"`.
         */
        "size"?: 'small' | 'default' | 'large';
        /**
          * The button type. Possible values are: `"primary"`, `"secondary"`, `"disabled"`.
         */
        "type"?: 'primary' | 'secondary' | 'disabled';
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "sd-button": SdButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "sd-button": LocalJSX.SdButton & JSXBase.HTMLAttributes<HTMLSdButtonElement>;
        }
    }
}
